services:
  - type: web
    name: bro-vs-bro-overlay
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PANEL_KEY
        sync: false
